version: 0.2

phases:   # github action의 jobs와 비슷한 의미
  build:
    commands:   # build 라는 작업 실행 시 실행될 shell 명령어들
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
      - echo $MONGO_URL
      - docker build -t project-flow-image --build-arg MONGO_URL=test --build-arg RABBIT_HOST=$RABBIT_HOST --build-arg RABBIT_PORT=$RABBIT_PORT --build-arg RABBIT_USERNAME=$RABBIT_USERNAME --build-arg RABBIT_PASSWORD=$RABBIT_PASSWORD --build-arg SECRET_KEY$SECRET_KEY .
      - "docker tag project-flow-image jhhong0509/project-flow:latest"

  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

  post_build:
    commands:
      - "docker push jhhong0509/project-flow:latest"

artifacts:    # artifact 설정
  files:      # appspec 파일 설정, 어떤 파일을 가져갈지 선택
    - appspec.yml
    - build/libs/*.jar
    - scripts/**
  discard-paths: yes  # CodeBuild의 결과물에 해당 파일들을 추가한다.

cache:
  paths:
    - '/root/.gradle/caches/**/*' # 캐싱된 위치