spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${MONGO_URL}
      database: project-flow

jwt:
  secret: ${SECRET_KEY:testtesttesttesttesttesttesttest}

rabbit:
  url: ${RABBIT_URL:localhost}
  port: ${RABBIT_PORT:5672}
  username: ${RABBIT_USERNAME:guest}
  password: ${RABBIT_PASSWORD:guest}