spring:
  data:
    mongodb:
      auto-index-creation: false
      authentication-database: admin
      uri: "mongodb+srv://hong:hong@project-flow.fyczq.mongodb.net/project-flow?retryWrites=true&w=majority"
      database: project-flow
rabbitmq:
  port: 61613
  username: guest
  password: guest
  host: 211.38.86.92
jwt:
  secret: Itiskindoffuntodotheimposiible1205!